// <auto-generated />
using DataTransferLawler.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DataTransferLawler.Migrations
{
    [DbContext(typeof(CountryContext))]
    partial class CountryContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.3")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DataTransferLawler.Models.Country", b =>
                {
                    b.Property<string>("CountryID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CountryFlag")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GameID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SportID")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("CountryID");

                    b.HasIndex("GameID");

                    b.HasIndex("SportID");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            CountryID = "can",
                            CountryFlag = "Canada.jpg",
                            GameID = "winter",
                            Name = "Canada",
                            SportID = "curl"
                        },
                        new
                        {
                            CountryID = "swe",
                            CountryFlag = "Sweden.jpg",
                            GameID = "winter",
                            Name = "Sweden",
                            SportID = "curl"
                        },
                        new
                        {
                            CountryID = "gb",
                            CountryFlag = "Britain.jpg",
                            GameID = "winter",
                            Name = "Great Britain",
                            SportID = "curl"
                        },
                        new
                        {
                            CountryID = "jam",
                            CountryFlag = "Jamaica.jpg",
                            GameID = "winter",
                            Name = "Jamaica",
                            SportID = "bob"
                        },
                        new
                        {
                            CountryID = "ita",
                            CountryFlag = "Italy.jpg",
                            GameID = "winter",
                            Name = "Italy",
                            SportID = "bob"
                        },
                        new
                        {
                            CountryID = "jap",
                            CountryFlag = "Japan.jpg",
                            GameID = "winter",
                            Name = "Japan",
                            SportID = "bob"
                        },
                        new
                        {
                            CountryID = "ger",
                            CountryFlag = "Germany.jpg",
                            GameID = "summer",
                            Name = "Germany",
                            SportID = "dive"
                        },
                        new
                        {
                            CountryID = "chi",
                            CountryFlag = "China.jpg",
                            GameID = "summer",
                            Name = "China",
                            SportID = "dive"
                        },
                        new
                        {
                            CountryID = "mex",
                            CountryFlag = "Maxico.jpg",
                            GameID = "summer",
                            Name = "Mexico",
                            SportID = "dive"
                        },
                        new
                        {
                            CountryID = "bra",
                            CountryFlag = "Brazil.jpg",
                            GameID = "summer",
                            Name = "Brazil",
                            SportID = "road"
                        },
                        new
                        {
                            CountryID = "net",
                            CountryFlag = "Netherlands.jpg",
                            GameID = "summer",
                            Name = "Netherlands",
                            SportID = "road"
                        },
                        new
                        {
                            CountryID = "usa",
                            CountryFlag = "USA.jpg",
                            GameID = "summer",
                            Name = "USA",
                            SportID = "road"
                        },
                        new
                        {
                            CountryID = "tha",
                            CountryFlag = "Thailand.jpg",
                            GameID = "para",
                            Name = "Thailand",
                            SportID = "arch"
                        },
                        new
                        {
                            CountryID = "uru",
                            CountryFlag = "Uruguay.jpg",
                            GameID = "para",
                            Name = "Uruguay",
                            SportID = "arch"
                        },
                        new
                        {
                            CountryID = "ukr",
                            CountryFlag = "Ukraine.jpg",
                            GameID = "para",
                            Name = "Ukraine",
                            SportID = "arch"
                        },
                        new
                        {
                            CountryID = "aus",
                            CountryFlag = "Austria.jpg",
                            GameID = "para",
                            Name = "Austria",
                            SportID = "canoe"
                        },
                        new
                        {
                            CountryID = "pak",
                            CountryFlag = "Pakistan.jpg",
                            GameID = "para",
                            Name = "Pakistan",
                            SportID = "canoe"
                        },
                        new
                        {
                            CountryID = "zim",
                            CountryFlag = "Zimbabwe.jpg",
                            GameID = "para",
                            Name = "Zimbabwe",
                            SportID = "canoe"
                        },
                        new
                        {
                            CountryID = "fra",
                            CountryFlag = "France.jpg",
                            GameID = "youth",
                            Name = "France",
                            SportID = "break"
                        },
                        new
                        {
                            CountryID = "cyp",
                            CountryFlag = "Cyprus.jpg",
                            GameID = "youth",
                            Name = "Cyprus",
                            SportID = "break"
                        },
                        new
                        {
                            CountryID = "rus",
                            CountryFlag = "Russia.jpg",
                            GameID = "youth",
                            Name = "Russia",
                            SportID = "break"
                        },
                        new
                        {
                            CountryID = "fin",
                            CountryFlag = "Finland.jpg",
                            GameID = "youth",
                            Name = "Finland",
                            SportID = "skate"
                        },
                        new
                        {
                            CountryID = "slo",
                            CountryFlag = "Slovakia.jpg",
                            GameID = "youth",
                            Name = "Slovakia",
                            SportID = "skate"
                        },
                        new
                        {
                            CountryID = "por",
                            CountryFlag = "Portugal.jpg",
                            GameID = "youth",
                            Name = "Portugal",
                            SportID = "skate"
                        });
                });

            modelBuilder.Entity("DataTransferLawler.Models.Game", b =>
                {
                    b.Property<string>("GameID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GameID");

                    b.ToTable("Games");

                    b.HasData(
                        new
                        {
                            GameID = "winter",
                            Name = "Winter Olympics"
                        },
                        new
                        {
                            GameID = "summer",
                            Name = "Summer Olympics"
                        },
                        new
                        {
                            GameID = "para",
                            Name = "Paralympics"
                        },
                        new
                        {
                            GameID = "youth",
                            Name = "Youth Olympic Games"
                        });
                });

            modelBuilder.Entity("DataTransferLawler.Models.Sport", b =>
                {
                    b.Property<string>("SportID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SportID");

                    b.ToTable("Sports");

                    b.HasData(
                        new
                        {
                            SportID = "curl",
                            Name = "Curling/Indoor"
                        },
                        new
                        {
                            SportID = "bob",
                            Name = "Bobsleigh/Outdoor"
                        },
                        new
                        {
                            SportID = "dive",
                            Name = "Diving/Indoor"
                        },
                        new
                        {
                            SportID = "road",
                            Name = "Road Cycling/Outdoor"
                        },
                        new
                        {
                            SportID = "arch",
                            Name = "Archery/Indoor"
                        },
                        new
                        {
                            SportID = "canoe",
                            Name = "Canoe Sprint/Outdoor"
                        },
                        new
                        {
                            SportID = "break",
                            Name = "Breakdancing/Indoor"
                        },
                        new
                        {
                            SportID = "skate",
                            Name = "Skateboarding/Outdoor"
                        });
                });

            modelBuilder.Entity("DataTransferLawler.Models.Country", b =>
                {
                    b.HasOne("DataTransferLawler.Models.Game", "Game")
                        .WithMany()
                        .HasForeignKey("GameID");

                    b.HasOne("DataTransferLawler.Models.Sport", "Sport")
                        .WithMany()
                        .HasForeignKey("SportID");

                    b.Navigation("Game");

                    b.Navigation("Sport");
                });
#pragma warning restore 612, 618
        }
    }
}
